{
  "check-coverage": false,
  "reporter": { "lcov", "text" },
  "include": [ "src/**/*.ts" ],
  "exclude": [ "test/**/*.spec.ts" ],
  "lines": 86,
  "statements": 80,
  "functions": 80,
  "branches": 60
}
